version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - "rymsha"
    reviewers:
      - "rymsha"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - "alansemenov"
    reviewers:
      - "alansemenov"
    ignore:
      - dependency-name: "@enonic/lib-admin-ui"
  - package-ecosystem: "npm"
    directory: "/testing"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - "alansemenov"
    reviewers:
      - "alansemenov"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    assignees:
      - "rymsha"
    reviewers:
      - "rymsha"
