/**
 * Created  on 23.09.2026
 */
module.exports = Object.freeze({
  SUITE_TIMEOUT: 180000,
  generateRandomName(part) {
    return part + Math.round(Math.random() * 1000000);
  },

  itemIsArchived(name) {
    return `Item "${name}" has been archived.`;
  },

  itemSavedNotificationMessage(name) {
    return `Item "${name}" has been saved.`;
  },
  languageCopiedNotification: (parent) => `Language has been copied from "${parent}"`,
  itemPublishedNotificationMessage: (name) => {
    return `Item "${name}" has been published.`;
  },

  projectCreatedMessage: (name) => `Project "${name}" has been created.`,
  projectNameAlreadyExistsMessage: (name) => `Project with name [${name}] already exists`,
  projectDeletedMessage: (name) => `Project "${name}" has been deleted.`,

  BROWSER_XP_TITLES: {
    CONTENT_STUDIO: 'Content Studio - Enonic XP Admin',
    XP_HOME: 'Enonic XP Home',
    APPLICATIONS_TITLE: `Applications - Enonic XP Admin`,
  },
  NOTIFICATION_MESSAGES: {
    PERMISSIONS_APPLIED: 'Permissions have been applied.',
    permissionsAppliedNotificationMessage: (name) => {
      return `Permissions for "${name}" are applied.`;
    },
  },
  TIMEOUT: {
    MEDIUM: 3000,
    LONG: 5000,
    SHORT: 2000,
  },
  TEST_DATA: {
    TEST_FOLDER_IMAGES_1_DISPLAY_NAME: 'All Content types images',
    TEST_FOLDER_IMAGES_1_NAME: 'all-content-types-images',
    FOLDER_WITH_IMAGES_2_DISPLAY_NAME: 'Images for simple page',
    FOLDER_WITH_IMAGES_2_NAME: 'imagearchive',
    SELENIUM_TESTS_FOLDER_DISPLAY_NAME: 'folder for selenium tests',
    SELENIUM_TESTS_FOLDER_NAME: 'selenium-tests-folder',
    IMPORTED_SITE_NAME: 'site040269',
    IMPORTED_SITE_837567: 'site837567',
    IMPORTED_SITE_622034: 'site622034',
    IMPORTED_SITE_916528: 'site916528',
    IMPORTED_SITE_954009: 'site954009',
    IMPORTED_SITE_579992: 'site579992',
    IMPORTED_ARTICLE_1: 'article1',
    IMPORTED_ARTICLE_2: 'article2',
    PARENT_FOLDER_498088: 'parent498088',
    CHILD_FOLDER_431583: 'child431583',
    PARENT_FOLDER_273049: 'folder273049',
    CHILD_FOLDER_865739: 'child865739',
  },
  TEST_APPS_NAME: {
    APP_CONTENT_TYPES: 'All Content Types App',
    SIMPLE_SITE_APP: 'Simple Site App',
    TEST_APP_WITH_METADATA_MIXIN: 'Test Selenium App',
    MY_FIRST_APP: 'My First App',
    TEST_ADFS_PROVIDER_APP: 'Test ADFS ID Provider',
  },

  PASSWORD: {
    MEDIUM: 'AUserA567$',
    STRONG: '1User%#567$=',
    WEAK: 'test12345',
  },

  VALIDATION_MESSAGE: {
    TEXT_IS_TOO_LONG: 'Text is too long',
  },
  ISSUES: {
    STATUS_CLOSED: 'Closed',
    STATUS_OPEN: 'Open',
    COMMENT_ADDED: 'Your comment is added to the task.',
  },
  BROWSER_WIDTH: 1950,
  BROWSER_HEIGHT: 1050,
  EMULATOR_RESOLUTION: {
    FULL_SIZE: 'Full Size',
    MEDIUM_PHONE: 'Medium Phone',
    LARGE_PHONE: 'Large Phone',
    TABLET: 'Tablet',
    NOTEBOOK_13: '13" Notebook',
    SMALL_PHONE: 'Small Phone',
    NOTEBOOK_15: '15" Notebook',
  },
  EMULATOR_RESOLUTION_VALUE: {
    FULL_SIZE: '100%',
    MEDIUM_PHONE: '375px',
    LARGE_PHONE: '414px',
    TABLET: '768px',
    NOTEBOOK_13: '1280px',
    SMALL_PHONE: '320px',
    NOTEBOOK_15: '1356px',
  },
  contentTypes: {
    SHORTCUT: 'Shortcut',
    FOLDER: `Folder`,
    SITE: 'Site',
    PAGE_TEMPLATE: 'Page Template',
    HTML_AREA_0_0: 'htmlarea0_0',
    HTML_AREA_0_2: 'htmlarea0_2',
    HTML_AREA_0_1: 'htmlarea0_1',
    HTML_AREA_1_1: 'htmlarea1_1',
    HTML_AREA_2_4: 'htmlarea2_4',
    IMG_SELECTOR_0_0: 'imageselector0_0',
    IMG_SELECTOR_ALLOW_SITE: 'imageselector_site',
    IMG_SELECTOR_0_1: 'imageselector0_1',
    IMG_SELECTOR_1_1: 'imageselector1_1',
    IMG_SEL_TOGGLE_HIDDEN: 'image-sel-toggle-hidden',
    IMG_SELECTOR_2_4: 'imageselector2_4',
    DOUBLE_MIN_MAX: 'double_max',
    DOUBLE_DEFAULT_2_4: 'double2_4_def',
    DOUBLE_0_1: 'double0_1',
    DOUBLE_0_0: 'double0_0',
    DOUBLE_1_1_X_DATA: 'double1_1',
    DOUBLE_2_4: 'double2_4',
    LONG_MIN_MAX: 'long_max',
    TEXTAREA_MAX_LENGTH: 'textarea_conf',
    TEXTLINE_MAX_LENGTH: 'textline_conf',
    TEXTLINE_REGEXP: 'text_line_regexp',
    TEXTLINE_0_1: 'textline0_1',
    TEXTLINE_1_0: 'textline1_0',
    TEXTLINE_1_1: 'textline1_1',
    GEOPOINT_0_0: 'geopoint0_0',
    GEOPOINT_1_1: 'geopoint1_1',
    TIME_0_1: 'time0_1',
    DATE_TIME_NOW_CONFIG: 'datetime now',
    DATE_TIME_1_1: 'datetime1_1',
    DATE_1_1: 'date1_1',
    ATTACHMENTS_1_1: 'attachment1_1',
    ATTACHMENTS_0_0: 'attachment0_0',
    LONG_0_1: 'long0_1',
    LONG_1_1: 'long1_1',
    LONG_2_4: 'long2_4',
    TEXT_AREA_1_1: 'textarea1_1',
    TEXT_AREA_0_1: 'textarea0_1',
    TEXT_AREA_2_4: 'textarea2_4',
    CHECKBOX_0_1: 'checkbox',
    CHECKBOX_1_1: 'checkbox_req',
    FIELDSET: 'fieldset',
    COMBOBOX_0_0: 'combobox0_0',
    COMBOBOX_1_1: 'combobox1_1',
    COMBOBOX_2_4: 'combobox2_4',
    RADIOBUTTON_1_1: 'radiobutton1_1',
    RADIOBUTTON_0_1: 'radiobutton0_1',
    TAG_2_5: 'tag2_5',
    TAG_0_5: 'tag0_5',
    CONTENT_SELECTOR_CONF: 'content-sel-conf1',
    CUSTOM_SELECTOR_0_2: 'custom-selector0_2',
    CUSTOM_SELECTOR_1_1: 'custom-selector1_1',
    CONTENT_SELECTOR_2_8: 'content-selector2_8',
    CONTENT_SELECTOR_1_2: 'content-selector1_2',
    EXPANDED_SINGLE_SELECTION_OPTION_SET: 'optionset-single-selection',
    OPTION_SET: 'optionset',
    OPTION_SET2: 'optionset2',
    OPTION_SET_1: 'optionset1',
    OPTION_SET_UNLIM: 'opt-set-unlim',
    OPTION_SET_0_2: 'optionset0_2',
    ITEM_SET_0_0: 'item-set0_0',
    SET_IN_SET: 'set-in-set',
    ARTICLE: 'article',
    ARTICLE_ALLOW_NON_EX: 'article non existing',
    ARTICLE_ALLOW_MEDIA_WILD_CARD: 'article wild card',
    ARTICLE_ALLOW_NON_MEDIA: 'article non media',
    CUSTOM_REL_0_1: 'custom-relationship0_1',
    CUSTOM_RELATIONSHIP: 'custom-relationship2_4',
    OPTION_SET_HELP_TEXT: 'optionset_help',
    PERSON: 'Person',
    LOCALE_CODE: 'Locale Code',
    FREE_FORM: 'freeform',
  },
  permissions: {
    FULL_ACCESS: 'Full Access',
    CUSTOM: 'Custom...',
    CAN_PUBLISH: 'Can Publish',
    CAN_READ: 'Can Read',
    CAN_WRITE: 'Can Write',
  },
  permissionOperation: {
    READ: 'Read',
    CREATE: 'Create',
    MODIFY: 'Modify',
    DELETE: 'Delete',
    PUBLISH: 'Publish',
    READ_PERMISSIONS: 'Read Permissions',
    WRITE_PERMISSIONS: 'Write Permissions',
  },
  roleName: {
    ADMINISTRATOR: 'system.admin',
    CM_ADMIN: 'cms.admin',
  },
  roleDisplayName: {
    CONTENT_MANAGER_APP: 'Content Manager App',
  },
  systemUsersDisplayName: {
    ANONYMOUS_USER: 'Anonymous User',
    EVERYONE: 'Everyone',
    SUPER_USER: 'Super User',
    ME: 'Me',
  },

  UNNAMED_CONTENT_DISPLAY_NAME: '<unnamed>',
  GRID_CONTEXT_MENU: {
    NEW: 'New',
    EDIT: 'Edit',
    DELETE: 'Delete',
    DUPLICATE: 'Duplicate',
    MOVE: 'Move',
    SORT: 'Sort',
    RESTORE: 'Restore',
    PREVIEW: 'Preview',
    PUBLISH: 'Publish',
    UNPUBLISH: 'Unpublish',
  },
  ICON_WORKFLOW_STATE: {
    IN_PROGRESS: 'in-progress',
    READY_FOR_PUBLISHING: 'ready',
    INVALID: 'invalid',
  },
  SYSTEM_ROLES_NAME: {
    ADMINISTRATOR: 'roles/system.admin',
    AUDIT_LOG: 'roles/system.auditlog',
  },
  SYSTEM_ROLES: {
    CM_ADMIN: 'Content Manager Administrator',
    ADMIN_CONSOLE: 'Administration Console Login',
    CM_APP: 'Content Manager App',
    CM_APP_EXPERT: 'Content Manager Expert',
    ADMINISTRATOR: 'Administrator',
    USERS_APP: 'Users App',
    AUTHENTICATED: 'Authenticated',
    USERS_ADMINISTRATOR: 'Users Administrator',
    EVERYONE: 'Everyone',
    AUDIT_LOG: 'Audit Log',
  },
  PREVIEW_PANEL_MESSAGE: {
    CAN_NOT_RENDER_NON_MEDIA: 'Can not render non-media content',
    PREVIEW_NOT_AVAILABLE: 'No preview available',
    CAN_NOT_RENDER_WITH_SITE_ENGINE: 'Can not render with site engine',
    PREVIEW_NOT_AVAILABLE_ADD_APP: 'Please add an application to your site to enable preview',
  },
  EXTENSIONS: {
    APPLICATIONS: 'Applications',
    SERVICE_ACCOUNTS: 'Service Accounts',
    USERS: 'Users',
    GROUPS: 'Groups',
    ROLES: 'Roles',
    ID_PROVIDERS: 'ID Providers',
  },
  // Access levels of the ID provider editor's Permissions step, widening (phrases:
  // idProviders.dialog.access.*).
  ID_PROVIDER_ACCESS: {
    READ: 'Read',
    CREATE_USERS: 'Create users',
    WRITE_USERS: 'Write users',
    ID_PROVIDER_MANAGER: 'ID provider manager',
    ADMINISTRATOR: 'Administrator',
  },
  // Items of the 'Sort by' menu in the browse list header (phrases: <section>.sort.*). Users and
  // Groups offer all four; Roles and ID Providers only the two by display name. Note the en dash.
  SORT_MENU_ITEM: {
    DISPLAY_NAME_ASC: 'Display name (A–Z)',
    DISPLAY_NAME_DESC: 'Display name (Z–A)',
    ID_PROVIDER_ASC: 'ID provider (A–Z)',
    ID_PROVIDER_DESC: 'ID provider (Z–A)',
  },
  // 'data-section' of the SectionMount that hosts the extension's shadow root
  SECTION_ID: {
    APPLICATIONS: 'com.enonic.xp.app.applications:applications',
    SERVICE_ACCOUNTS: 'com.enonic.xp.app.users:service-accounts',
    USERS: 'com.enonic.xp.app.users:users',
    GROUPS: 'com.enonic.xp.app.users:groups',
    ROLES: 'com.enonic.xp.app.users:roles',
    ID_PROVIDERS: 'com.enonic.xp.app.users:id-providers',
  },
});
